AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Partner Pipeline Analysis - App Runner with File Configuration'

Parameters:
  AppName:
    Type: String
    Default: 'aws-partner-hygiene'
    Description: 'Name for the application'

Resources:
  # App Runner Service using file-based configuration
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Sub '${AppName}-service'
      SourceConfiguration:
        AutoDeploymentsEnabled: true
        CodeRepository:
          RepositoryUrl: 'https://github.com/gclopesaws/aws-partner-hygiene'
          SourceCodeVersion:
            Type: BRANCH
            Value: 'main'
          CodeConfiguration:
            ConfigurationSource: REPOSITORY
      InstanceConfiguration:
        Cpu: '0.5 vCPU'
        Memory: '1 GB'
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: '/'
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 5

Outputs:
  AppRunnerServiceUrl:
    Description: 'URL of the deployed Streamlit application'
    Value: !Sub 'https://${AppRunnerService.ServiceUrl}'
  
  AppRunnerServiceArn:
    Description: 'ARN of the App Runner service'
    Value: !GetAtt AppRunnerService.ServiceArn
  
  Instructions:
    Description: 'Next steps'
    Value: 'Wait 5-10 minutes for build to complete, then access the URL above'